[platformio]
src_dir = firmware

[env:artemis_atp]
platform = https://github.com/nigelb/platform-apollo3blue
board = SparkFun_RedBoard_Artemis_ATP
framework = arduino

; Arduino_Apollo3 core selection (v2)
platform_packages = framework-arduinoapollo3@https://github.com/sparkfun/Arduino_Apollo3#v2.2.0

; Build directly from /firmware, exclude main.cpp (use harness_tester.ino instead)
build_src_filter = +<*> -<main.cpp>

upload_protocol = jlink
debug_tool = jlink

monitor_speed = 115200
